# 配置项目名和session的过期时间
server:
  servlet:
    session:
      timeout: 60m
  tomcat:
    uri-encoding: UTF-8
  port: 8080
# 日志的存放位置与级别
logging:
  file:
    name: log/workpan.log
  level:
    root: info
# 配置Mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


spring:
  #  静态资源的访问路径
  mvc:
    static-path-pattern: /**
  datasource:
    # 配置数据源
    username: root
    password: XXXX
    url: jdbc:mysql://XXXXXX:3306/cloud1?serverTimezone=Hongkong&useAffectedRows=true&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置druid数据源
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  # 配置文件上传相关
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  # 邮件相关
  mail:
    host: smtp.qq.com
    username: XX@qq.com
    #授权密码
    password: gcjlotqdweivbaha
    default-encoding: utf-8


